var kioskapp =angular.module("kioskapp",[
	'ngRoute',
	'loginController',
	'mainmenuController',
	'AccessServices',
	'applicationController',
	'applicationService'

	]);
kioskapp.config(["$routeProvider",
	function($routeProvider){
		$routeProvider.
			when('/login',{
				templateUrl:'partials/Login.html',
				controller:'LoginCtrl'
			}).
			when('/menu',{
				templateUrl:'partials/mainmenus.html',
				controller:'MainMenuCtrl'
			}).
			when('/absencelist',{
				templateUrl:'partials/absencelist.html',
				controller:'applicationCtrl'
			}).
			when('/addabsence/:reqId',{
				templateUrl:'partials/addabsence.html',
				controller:'AddabsenceCtrl'
			}).
			when('/timeaccount',{
				templateUrl:'partials/timeaccount.html',
				controller:'TimeAccCtrl'
			}).
			when('/timerecords',{
				templateUrl:'partials/timerecord.html',
				controller:'TimeRecCtrl'
			}).
			when('/addtimerecord/:reqId',{
				templateUrl:'partials/addnewtimerec.html',
				controller:'AddTimeRecCtrl'
			}).
			when('/timestatus',{
				templateUrl:'partials/timestatus.html',
				controller:"TimeStatusCtrl"
			}).
			when("/viewer/:page/:date",{
				templateUrl:'partials/pdfviewer.html',
				controller:'PDFViwerCtrl'
			}).
			when("/certification",{
				templateUrl:'partials/certification.html',
				controller:'CertifCtrl'
			}).
			when("/payment",{
				templateUrl:"partials/payment.html",
				controller:"PaymentCtrl"
			}).
			when("/accountaddress",{
				templateUrl:"partials/accountaddress.html",
				controller:"AccountCtrl"
			}).
			when("/accountbank",{
				templateUrl:"partials/accountbank.html",
				controller:"AccountCtrl"
			}).
			when("/accounttravel",{
				templateUrl:"partials/accounttravel.html",
				controller:"AccountCtrl"
			}).
			when("/addaddress/:id",{
				templateUrl:"partials/addadress.html",
				controller:"AddAddressCtrl"
			}).
			when("/addbank/:id",{
				templateUrl:"partials/addnewbank.html",
				controller:"AddBankCtrl"
			}).
			when("/addTravel/:id",{
				templateUrl:"partials/addTravel.html",
				controller:"AddTravelCtrl"
			}).
			when("/services",{
				templateUrl:"partials/services.html",
				controller:"ServiceCtrl"
			}).
			when("/search",{
				templateUrl:"partials/search.html",
				controller:"SearchCtrl"
			}).
			when("/inbox",{
				templateUrl:"partials/mailinbox.html",
				controller:"MailCtrl"
			}).
			when("/outbox",{
				templateUrl:"partials/mailoutbox.html",
				controller:"MailCtrl"
			}).
			when("/sendmail",{
				templateUrl:"partials/sendmail.html",
				controller:"MailCtrl"
			}).
			when("/openmail",{
				templateUrl:"partials/openmail.html",
				controller:"MailCtrl"
			}).
			otherwise({
        		redirectTo: '/login'
      		});

	}
	]);
kioskapp.controller("NavController",["$scope","Login","$route",
	function($scope,Login,$route){
		var authUser=Login.getLoggedUser();
		$scope.loggedin=false;
		if(authUser!=null)
		{
			$scope.userFirstName=authUser.FirstName;
			$scope.userLastName=authUser.Name;
			$scope.userID=authUser.id;
			$scope.loggedin=true;
		}
		$scope.loggout=function(){
			 Login.logout();
			 $scope.$on('$locationChangeSuccess',function(e,next,current){
			 	window.location.reload();
			 });
		}
	}
	]);
